version: "3.0"

services:
  express-template:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  managementapp:
    image: nginx
    build:
      context: ./managementapp
      dockerfile: clientDockerfile
    ports:
      - 4200:80
